name: Build and Deploy
on:
  push:
    branches: [dev-v4]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 15

      - name: Install and Build 🔧
        run: |
          npm install
          npm run predeploy

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: frontend/build # The folder the action should deploy.